### ISSUE TITLE
Abrakadabra in convert

### ISSUE THREAD

**Issue by SergeyDjam** [sanzoghenzo/markdownr#15]
# Ð¡Ð¨Ð Ð¿Ð¾ÑÑÐ°Ð²Ð¸Ð»Ð¸ Ð¿Ð¾Ð´Ð½Ð¾Ð¶ÐºÑ ÐºÐ¸ÑÐ°Ð¹ÑÐºÐ¾Ð¹ Ð¿Ð¾Ð»ÑÐ¿ÑÐ¾Ð²Ð¾Ð´Ð½Ð¸ÐºÐ¾Ð²Ð¾Ð¹ Ð¿ÑÐ¾Ð¼ÑÑÐ»ÐµÐ½Ð½Ð¾ÑÑÐ¸: Ñ ÐÐ¸ÑÐ°Ñ Ð½ÐµÑ Ð·Ð°Ð¼ÐµÐ½Ñ Ð°Ð¼ÐµÑÐ¸ÐºÐ°Ð½ÑÐºÐ¾Ð¼Ñ ÑÐ¾ÑÑÑ

Clipped from: https://a.devs.today/3dnews.ru/1072168

Ð Ð¼Ð¸Ð½ÑÐ²ÑÑÑ Ð¿ÑÑÐ½Ð¸ÑÑ Ð¡Ð¨Ð [Ð²Ð²ÐµÐ»Ð¸ Ð½Ð¾Ð²ÑÐµ Ð¿ÑÐ°Ð²Ð¸Ð»Ð° ÑÐºÑÐ¿Ð¾ÑÑÐ½Ð¾Ð³Ð¾ ÐºÐ¾Ð½ÑÑÐ¾Ð»Ñ](https://3dnews.ru/1072082/ssha-ogranichat-eksport-nekotorih-chipov-chtobi-predotvratit-ih-zlonamerennoe-ispolzovanie) Ð² Ð¾ÑÐ½Ð¾ÑÐµÐ½Ð¸Ð¸ ÐÐ¸ÑÐ°Ñ, ÐºÑÐ¾Ð¼Ðµ Ð¿ÑÐ¾ÑÐµÐ³Ð¾ Ð·Ð°Ð¿ÑÐµÑÐ¸Ð² Ð¿ÑÐ¾Ð´Ð°Ð²Ð°ÑÑ ÐºÐ¾Ð¼Ð¿Ð°Ð½Ð¸ÑÐ¼ Ð¸Ð· ÐÐ¾Ð´Ð½ÐµÐ±ÐµÑÐ½Ð¾Ð¹ Ð¿ÑÐ¾Ð³ÑÐ°Ð¼Ð¼Ð½Ð¾Ðµ Ð¾Ð±ÐµÑÐ¿ÐµÑÐµÐ½Ð¸Ðµ, ÐºÐ¾ÑÐ¾ÑÐ¾Ðµ Ð¼Ð¾Ð¶ÐµÑ ÑÐ»ÑÐ¶Ð¸ÑÑ Ð´Ð»Ñ ÑÐ°Ð·ÑÐ°Ð±Ð¾ÑÐºÐ¸ Ð¿ÐµÑÐµÐ´Ð¾Ð²ÑÑ ÑÐ¸Ð¿Ð¾Ð² (Ñ ÑÑÐ°Ð½Ð·Ð¸ÑÑÐ¾ÑÐ°Ð¼Ð¸ GAAFET). ÐÑÐµÐ²Ð¸Ð´Ð½Ð¾, ÑÑÐ¾ ÑÑÐ¾ Ð½ÐµÐ³Ð°ÑÐ¸Ð²Ð½Ð¾ Ð¾ÑÑÐ°Ð·Ð¸ÑÑÑ Ð½Ð° ÐºÐ¸ÑÐ°Ð¹ÑÐºÐ¾Ð¹ Ð¿Ð¾Ð»ÑÐ¿ÑÐ¾Ð²Ð¾Ð´Ð½Ð¸ÐºÐ¾Ð²Ð¾Ð¹ Ð¸Ð½Ð´ÑÑÑÑÐ¸Ð¸ Ð¸ Ð°Ð½Ð°Ð»Ð¸ÑÐ¸ÑÐµÑÐºÐ¾Ðµ Ð°Ð³ÐµÐ½ÑÑÑÐ²Ð¾ TrendForce Ð¾Ð±ÑÑÑÐ½Ð¸Ð»Ð¾ Ð¿Ð¾ÑÐµÐ¼Ñ.

![ ÐÑÑÐ¾ÑÐ½Ð¸Ðº Ð¸Ð·Ð¾Ð±ÑÐ°Ð¶ÐµÐ½Ð¸Ñ: Denny MÃ¼ller/unsplash.com ](https://3dnews.ru/assets/external/illustrations/2022/08/15/1072168/sm.53457-2af01bfb4681.750.jpg)

ÐÑÑÐ¾ÑÐ½Ð¸Ðº Ð¸Ð·Ð¾Ð±ÑÐ°Ð¶ÐµÐ½Ð¸Ñ: Denny MÃ¼ller/unsplash.com

ÐÐ¾ Ð¾ÑÐµÐ½ÐºÐ°Ð¼ Ð°Ð³ÐµÐ½ÑÑÑÐ²Ð°, Ð³Ð»Ð¾Ð±Ð°Ð»ÑÐ½ÑÐ¹ ÑÑÐ½Ð¾Ðº Ð¿ÑÐ¾Ð³ÑÐ°Ð¼Ð¼Ð½Ð¾Ð³Ð¾ Ð¾Ð±ÐµÑÐ¿ÐµÑÐµÐ½Ð¸Ñ Ð´Ð»Ñ Ð°Ð²ÑÐ¾Ð¼Ð°ÑÐ¸Ð·Ð°ÑÐ¸Ð¸ ÑÐ»ÐµÐºÑÑÐ¾Ð½Ð½Ð¾Ð³Ð¾ Ð¿ÑÐ¾ÐµÐºÑÐ¸ÑÐ¾Ð²Ð°Ð½Ð¸Ñ (EDA) Ñ 2020 Ð¿Ð¾ 2024 Ð³Ð¾Ð´Ñ Ð²ÑÑÐ°ÑÑÐµÑ Ñ $8,1 Ð¼Ð»ÑÐ´ Ð´Ð¾ $13,6 Ð¼Ð»ÑÐ´, Ð³Ð¾Ð´Ð¾Ð²Ð¾Ð¹ Ð¿ÑÐ¸ÑÐ¾ÑÑ ÑÐ¾ÑÑÐ°Ð²Ð¸Ñ 13,8 %. ÐÐ°Ð¶Ð½Ð¾ ÑÐ¾, ÑÑÐ¾ Ð½Ð° ÑÑÐ½ÐºÐµ Ð¿ÑÐ¾Ð³ÑÐ°Ð¼Ð¼Ð½Ð¾Ð³Ð¾ Ð¾Ð±ÐµÑÐ¿ÐµÑÐµÐ½Ð¸Ñ Ð´Ð»Ñ Ð¿ÑÐ¾ÐµÐºÑÐ¸ÑÐ¾Ð²Ð°Ð½Ð¸Ñ ÑÐ¾Ð²ÑÐµÐ¼ÐµÐ½Ð½ÑÑ ÑÐ¸Ð¿Ð¾Ð² Ð´ÐµÐ¹ÑÑÐ²ÑÑÑ Ð²ÑÐµÐ³Ð¾ Ð½ÐµÑÐºÐ¾Ð»ÑÐºÐ¾ ÐºÑÑÐ¿Ð½ÑÑ Ð¸Ð³ÑÐ¾ÐºÐ¾Ð², Ð²ÐºÐ»ÑÑÐ°Ñ Synopsys, Cadence Ð¸ Siemens. ÐÐ¾ Ð´Ð°Ð½Ð½ÑÐ¼ Ð°Ð½Ð°Ð»Ð¸ÑÐ¸ÐºÐ¾Ð², Ð² 2021 Ð³Ð¾Ð´Ñ Ð½Ð° Ð½Ð¸Ñ Ð¿ÑÐ¸ÑÐ¾Ð´Ð¸Ð»Ð¾ÑÑ 32 %, 30 % Ð¸ 13 % ÑÑÐ½ÐºÐ° ÑÐ¾Ð¾ÑÐ²ÐµÑÑÑÐ²ÐµÐ½Ð½Ð¾ â Ð²ÑÐµÐ³Ð¾ 75 %.

ÐÐ»Ñ Ð¾ÑÐµÐ½ÐºÐ¸ ÑÑÑÐµÐºÑÐ°, ÐºÐ¾ÑÐ¾ÑÑÐ¹ ÑÐ¿Ð¾ÑÐ¾Ð±Ð½Ñ Ð¾ÐºÐ°Ð·Ð°ÑÑ ÑÐ°Ð½ÐºÑÐ¸Ð¸ Ð½Ð° ÐºÐ¸ÑÐ°Ð¹ÑÐºÑÑ Ð¸Ð½Ð´ÑÑÑÑÐ¸Ñ Ð² ÑÐµÐ»Ð¾Ð¼, Ð´Ð¾ÑÑÐ°ÑÐ¾ÑÐ½Ð¾ Ð²ÑÐ¿Ð¾Ð¼Ð½Ð¸ÑÑ, ÑÑÐ¾ Ð² 2019 Ð³Ð¾Ð´Ñ Ð¡Ð¨Ð Ð²Ð½ÐµÑÐ»Ð¸ Ð² ÑÑÑÐ½ÑÐ¹ ÑÐ¿Ð¸ÑÐ¾Ðº Ð¿ÑÐ¸Ð½Ð°Ð´Ð»ÐµÐ¶Ð°ÑÑÑ Huawei Ð¿Ð¾Ð»ÑÐ¿ÑÐ¾Ð²Ð¾Ð´Ð½Ð¸ÐºÐ¾Ð²ÑÑ ÐºÐ¾Ð¼Ð¿Ð°Ð½Ð¸Ñ HiSilicon, Ð ÑÐ°ÑÑÐ½Ð¾ÑÑÐ¸, ÑÐ°Ð½ÐºÑÐ¸Ð¸ ÑÐ°ÑÐ¿ÑÐ¾ÑÑÑÐ°Ð½Ð¸Ð»Ð¸ÑÑ Ð·Ð°ÑÑÐ¾Ð½ÑÐ»Ð¸ ÑÐ°Ð±Ð¾ÑÑ ÐºÐ¸ÑÐ°Ð¹ÑÐºÐ¾Ð¹ ÐºÐ¾Ð¼Ð¿Ð°Ð½Ð¸Ð¸ Ñ Ð°Ð¼ÐµÑÐ¸ÐºÐ°Ð½ÑÐºÐ¸Ð¼Ð¸ Synopsys Ð¸ Cadence. Ð¥Ð¾ÑÑ Ð² ÑÐµÐ»Ð¾Ð¼ Ð¸Ð½Ð´ÑÑÑÑÐ¸Ñ Ð¿ÑÐ°ÐºÑÐ¸ÑÐµÑÐºÐ¸ Ð½Ðµ Ð¿Ð¾ÑÑÑÐ°Ð´Ð°Ð»Ð°, Ð±Ð¸Ð·Ð½ÐµÑÑ Huawei Ð² ÑÐ¾Ð¾ÑÐ²ÐµÑÑÑÐ²ÑÑÑÐµÐ¹ ÑÑÐµÑÐµ, Ð¿Ð¾ Ð´Ð°Ð½Ð½ÑÐ¼ TrendForce, Ð±ÑÐ» Ð½Ð°Ð½ÐµÑÑÐ½ Ð·Ð½Ð°ÑÐ¸ÑÐµÐ»ÑÐ½ÑÐ¹ ÑÑÐµÑÐ±.

![ ÐÑÑÐ¾ÑÐ½Ð¸Ðº Ð¸Ð·Ð¾Ð±ÑÐ°Ð¶ÐµÐ½Ð¸Ñ: TrendForce ](https://3dnews.ru/assets/external/illustrations/2022/08/15/1072168/20220eda1.jpg)

ÐÑÑÐ¾ÑÐ½Ð¸Ðº Ð¸Ð·Ð¾Ð±ÑÐ°Ð¶ÐµÐ½Ð¸Ñ: TrendForce

ÐÐ¸Ð´ÐµÑÐ¾Ð¼ Ð² ÑÐ°Ð·ÑÐ°Ð±Ð¾ÑÐºÐµ ÐºÐ¸ÑÐ°Ð¹ÑÐºÐ¸Ñ EDA-ÑÐµÑÐµÐ½Ð¸Ð¹ ÑÐ²Ð»ÑÐµÑÑÑ ÐºÐ¾Ð¼Ð¿Ð°Ð½Ð¸Ñ Empyrean Technology, Ð½Ð¾ ÐµÑ Ð²Ð»Ð¸ÑÐ½Ð¸Ðµ Ð¸ Ð´Ð¾ÑÐ¾Ð´Ñ Ð¿Ð¾ÐºÐ° ÐºÑÐ°Ð¹Ð½Ðµ Ð½ÐµÐ²ÐµÐ»Ð¸ÐºÐ¸ Ð² ÑÑÐ°Ð²Ð½ÐµÐ½Ð¸Ð¸ Ñ Ð°Ð¼ÐµÑÐ¸ÐºÐ°Ð½ÑÐºÐ¸Ð¼Ð¸ ÑÐ°Ð·ÑÐ°Ð±Ð¾ÑÑÐ¸ÐºÐ°Ð¼Ð¸ EDA. ÐÑÐ»Ð¸ ÐºÐ¸ÑÐ°Ð¹ÑÐºÐ¸Ð¹ ÑÐ¾ÑÑ Ð´Ð»Ñ ÑÐ°Ð·ÑÐ°Ð±Ð¾ÑÐºÐ¸ Ð°Ð½Ð°Ð»Ð¾Ð³Ð¾Ð²ÑÑ Ð¼Ð¸ÐºÑÐ¾ÑÑÐµÐ¼ Ð¸ ÑÐµÑÐµÐ½Ð¸Ð¹ Ð´Ð»Ñ Ð¿Ð°Ð½ÐµÐ»ÐµÐ¹ Ð´Ð¸ÑÐ¿Ð»ÐµÐµÐ² ÑÐ¶Ðµ Ð´Ð¾ÑÑÐ°ÑÐ¾ÑÐ½Ð¾ Ð·ÑÐµÐ»ÑÐµ, ÑÐ¾, Ð½Ð°Ð¿ÑÐ¸Ð¼ÐµÑ, Ð¿ÑÐ¾Ð³ÑÐ°Ð¼Ð¼Ð½Ð¾Ðµ Ð¾Ð±ÐµÑÐ¿ÐµÑÐµÐ½Ð¸Ðµ Ð´Ð»Ñ ÑÐ°Ð·ÑÐ°Ð±Ð¾ÑÐºÐ¸ ÑÐ¸ÑÑÐ¾Ð²ÑÑ ÑÐ¸Ð¿Ð¾Ð² Ð²Ð¾ Ð¼Ð½Ð¾Ð³Ð¾Ð¼ Ð¾ÑÑÑÐ°ÑÑ Ð¾Ñ ÑÐ°Ð·ÑÐ°Ð±Ð¾ÑÐ¾Ðº Ð°Ð¼ÐµÑÐ¸ÐºÐ°Ð½ÑÐºÐ¸Ñ ÐºÐ¾Ð½ÐºÑÑÐµÐ½ÑÐ¾Ð² Ð¸ Ð¿Ð¾ÐºÐ° Ð½Ðµ Ð³Ð¾ÑÐ¾Ð²Ð¾ Ð´Ð»Ñ ÑÐ°Ð·ÑÐ°Ð±Ð¾ÑÐºÐ¸ ÑÐµÑÐµÐ½Ð¸Ð¹ Ð½Ð¾Ð²Ð¾Ð³Ð¾ Ð¿Ð¾ÐºÐ¾Ð»ÐµÐ½Ð¸Ñ.

ÐÑÐ»Ð¸ Ð´Ð°Ð¶Ðµ ÐÐ¸ÑÐ°Ð¹ Ð¸Ð¼ÐµÐµÑ Ð±Ð¾Ð»ÑÑÐ¾Ð¹ Ð·Ð°Ð¿Ð°Ñ Ð»Ð¸ÑÐµÐ½Ð·Ð¸Ð¹ Ð½Ð° Ð°Ð¼ÐµÑÐ¸ÐºÐ°Ð½ÑÐºÐ¾Ðµ Ð¿ÑÐ¾Ð³ÑÐ°Ð¼Ð¼Ð½Ð¾Ðµ Ð¾Ð±ÐµÑÐ¿ÐµÑÐµÐ½Ð¸Ðµ, ÐµÐ³Ð¾ Ð²ÑÑ ÑÐ°Ð²Ð½Ð¾ Ð¿ÑÐ¸Ð´ÑÑÑÑ Ð¿Ð¾Ð´ÐºÐ»ÑÑÐ°ÑÑ Ðº Ð¡ÐµÑÐ¸ Ð´Ð»Ñ Ð¾Ð±Ð½Ð¾Ð²Ð»ÐµÐ½Ð¸Ð¹ Ð¸ Ð¸Ñ Ð¸Ð·-Ð·Ð° ÑÐ°Ð½ÐºÑÐ¸Ð¹ Ð¿ÑÐµÐ´Ð¾ÑÑÐ°Ð²Ð»ÐµÐ½Ð¾ ÑÐ¶Ðµ Ð½Ðµ Ð±ÑÐ´ÐµÑ. ÐÑÑÐ³Ð¸Ð¼Ð¸ ÑÐ»Ð¾Ð²Ð°Ð¼Ð¸, Ð²ÐµÑÑ Ð¿ÑÐ¾ÑÐµÑÑ Ð±ÑÐ´ÐµÑ ÐºÐ¾Ð½ÑÑÐ¾Ð»Ð¸ÑÐ¾Ð²Ð°ÑÑ Ð¸ Ð¾Ð³ÑÐ°Ð½Ð¸ÑÐ¸Ð²Ð°ÑÑÑÑ Ð¸Ð· Ð¡Ð¨Ð â ÑÐ°Ð½ÐºÑÐ¸Ð¾Ð½Ð½ÑÐ¹ Ð¾Ð¿ÑÑ Ð Ð¾ÑÑÐ¸Ð¸ Ð¿Ð¾ÐºÐ°Ð·Ð°Ð», ÑÑÐ¾ Ð·Ð°Ð¿Ð°Ð´Ð½ÑÐµ ÐºÐ¾Ð¼Ð¿Ð°Ð½Ð¸Ð¸ ÑÐ¿Ð¾ÑÐ¾Ð±Ð½Ñ Ð»Ð¸ÑÐ°ÑÑ ÐºÐ»Ð¸ÐµÐ½ÑÐ¾Ð² Ð´Ð¾ÑÑÑÐ¿Ð° Ð´Ð°Ð¶Ðµ Ðº ÑÐ¶Ðµ Ð¾Ð¿Ð»Ð°ÑÐµÐ½Ð½ÑÐ¼ ÑÐµÑÐ²Ð¸ÑÐ°Ð¼ Ð¸ ÐÐ.

![ ÐÑÑÐ¾ÑÐ½Ð¸Ðº Ð¸Ð·Ð¾Ð±ÑÐ°Ð¶ÐµÐ½Ð¸Ñ: TrendForce ](https://3dnews.ru/assets/external/illustrations/2022/08/15/1072168/20220eda2.jpg)

ÐÑÑÐ¾ÑÐ½Ð¸Ðº Ð¸Ð·Ð¾Ð±ÑÐ°Ð¶ÐµÐ½Ð¸Ñ: TrendForce

Ð¥Ð¾ÑÑ Ð² ÐºÑÐ°ÑÐºÐ¾ÑÑÐ¾ÑÐ½Ð¾Ð¹ Ð¿ÐµÑÑÐ¿ÐµÐºÑÐ¸Ð²Ðµ ÐºÐ¸ÑÐ°Ð¹ÑÐºÐ¸Ð¼ ÑÐ°Ð·ÑÐ°Ð±Ð¾ÑÑÐ¸ÐºÐ°Ð¼, ÐºÐ°Ðº Ð¾Ð¶Ð¸Ð´Ð°ÐµÑÑÑ, Ð½Ðµ Ð¿Ð¾Ð½Ð°Ð´Ð¾Ð±Ð¸ÑÑÑ ÑÐ¾ÑÑ Ð´Ð»Ñ ÑÐ°Ð·ÑÐ°Ð±Ð¾ÑÐºÐ¸ ÑÐ¸Ð¿Ð¾Ð² Ñ ÑÑÐ°Ð½Ð·Ð¸ÑÑÐ¾ÑÐ°Ð¼Ð¸ GAAFET, Ð¾Ð½ Ð½ÐµÐ¾Ð±ÑÐ¾Ð´Ð¸Ð¼ Ð´Ð»Ñ ÑÐ°Ð·ÑÐ°Ð±Ð¾ÑÐºÐ¸ ÑÐ¸Ð¿Ð¾Ð² Ð² ÑÐ¾Ð¾ÑÐ²ÐµÑÑÑÐ²Ð¸Ð¸ Ñ 3-Ð½Ð¼ ÑÐµÑÐ¿ÑÐ¾ÑÐµÑÑÐ°Ð¼Ð¸ Ð² Ð±Ð»Ð¸Ð¶Ð°Ð¹ÑÐ¸Ðµ 3-5 Ð»ÐµÑ. ÐÐµÐ· Ð°Ð¼ÐµÑÐ¸ÐºÐ°Ð½ÑÐºÐ¸Ñ Ð¿ÑÐ¾Ð³ÑÐ°Ð¼Ð¼Ð½ÑÑ Ð¸Ð½ÑÑÑÑÐ¼ÐµÐ½ÑÐ¾Ð² Ñ ÐºÐ¸ÑÐ°Ð¹ÑÐºÐ¸Ñ ÑÐ°Ð·ÑÐ°Ð±Ð¾ÑÑÐ¸ÐºÐ¾Ð² Ð¾Ð±ÑÐ·Ð°ÑÐµÐ»ÑÐ½Ð¾ Ð²Ð¾Ð·Ð½Ð¸ÐºÐ½ÑÑ Ð·Ð½Ð°ÑÐ¸ÑÐµÐ»ÑÐ½ÑÐµ Ð¿ÑÐ¾Ð±Ð»ÐµÐ¼Ñ Ñ ÑÐ¾Ð·Ð´Ð°Ð½Ð¸ÐµÐ¼ ÑÐ¾Ð²ÑÐµÐ¼ÐµÐ½Ð½ÑÑ ÑÐµÑÐµÐ½Ð¸Ð¹. ÐÐ¾Ð»ÐµÐµ ÑÐ¾Ð³Ð¾, ÑÐ¾Ð¾ÑÐ²ÐµÑÑÑÐ²ÑÑÑÐµÐµ ÐÐ Ð¿Ð¾ÑÑÐµÐ±ÑÐµÑÑÑ Ð¸ ÐºÐ¸ÑÐ°Ð¹ÑÐºÐ¸Ð¼ ÐºÐ¾Ð½ÑÑÐ°ÐºÑÐ½ÑÐ¼ Ð¿ÑÐ¾Ð¸Ð·Ð²Ð¾Ð´Ð¸ÑÐµÐ»ÑÐ¼ ÑÐ¸Ð¿Ð¾Ð², Ð¿Ð¾ÑÑÐ¾Ð¼Ñ Ð¾Ð³ÑÐ°Ð½Ð¸ÑÐµÐ½Ð¸Ñ, Ð½Ð°Ð»Ð°Ð³Ð°ÐµÐ¼ÑÐµ Ð¡Ð¨Ð Ð½Ð° Ð¿ÑÐ¾Ð´Ð°Ð¶Ñ ÑÐ¾ÑÑÐ° Ð¸ Ð¾Ð±Ð¾ÑÑÐ´Ð¾Ð²Ð°Ð½Ð¸Ñ Ð´Ð»Ñ Ð¿ÑÐ¾Ð¸Ð·Ð²Ð¾Ð´ÑÑÐ²Ð°, Ð¼Ð¾Ð³ÑÑ Ð¾ÐºÐ°Ð·Ð°ÑÑ Ð´Ð¾Ð»Ð³Ð¾Ð²ÑÐµÐ¼ÐµÐ½Ð½ÑÐ¹ Ð½ÐµÐ³Ð°ÑÐ¸Ð²Ð½ÑÐ¹ ÑÑÑÐµÐºÑ Ð½Ð° ÐºÐ¸ÑÐ°Ð¹ÑÐºÑÑ Ð¿Ð¾Ð»ÑÐ¿ÑÐ¾Ð²Ð¾Ð´Ð½Ð¸ÐºÐ¾Ð²ÑÑ Ð¸Ð½Ð´ÑÑÑÑÐ¸Ñ.

ÐÑÐ»Ð¸ Ð²Ñ Ð·Ð°Ð¼ÐµÑÐ¸Ð»Ð¸ Ð¾ÑÐ¸Ð±ÐºÑ â Ð²ÑÐ´ÐµÐ»Ð¸ÑÐµ ÐµÐµ Ð¼ÑÑÑÑ Ð¸ Ð½Ð°Ð¶Ð¼Ð¸ÑÐµ CTRL+ENTER.

**Comment by sanzoghenzo** [comment]
Hi, 
This definetiley looks like an encoding/unicode issue, honestly I didn't test it...
I'll take a look at this ASAP

**Comment by sanzoghenzo** [comment]
As you can see from the related PR, I solved this particular issue;
I didn't test it as much as I should to ensure that nothing else is broken!
