### ISSUE TITLE
Share button is broken

### ISSUE THREAD

**Issue by Silverhawk85** [sanzoghenzo/markdownr#3]
It seems as if the share button is broken.
When I press it, nothing happens.

**Comment by sanzoghenzo** [comment]
Hi @Silverhawk85 ,
I'm sorry it doesn't work for you. 
Could you please tell me what's your phone and the android version?

**Comment by Silverhawk85** [comment]
Hello,

I have a Samsung Galaxy A6+.

My Android Version is 10.

Kind Regards

Markus


Andrea Ghensi ***@***.***> schrieb am Mi., 11. Mai 2022,
08:38:

**Comment by k2arim99** [comment]
I'm having similar issues with this bigass link
https://kaiserreich.fandom.com/wiki/Timeline_of_World_History_since_1914
It converts (I can see the preview) but cannot share nor it autopens the share menu
I'm using a redmi 10 and this only happens with this link afaik

**Comment by sanzoghenzo** [comment]
It seems that  `share_plus` has some size limitations/bug, somewhere inside of `Share.share` the message gets lost (and a null is returned).
I'm not so good with Android studio, so I cannot find what is going wrong (no errors are logged, at least from what I can understand).

I'm afraid I have no solutions for this; I can propose a workaround: adding a "Copy" button to send the text to the clipboard.

**Comment by Silverhawk85** [comment]
Hello,

I found out, that this error only occures when I try to share
https://www.gog.com/
Other Sites work. I can't say what is the difference between other URLs.

And yes, you understood right.
Converting works. Then the share button activates but when you touch the
share button no menu opens for sharing it.



Andrea Ghensi ***@***.***> schrieb am Mi., 11. Mai 2022,
10:13:

**Comment by sanzoghenzo** [comment]
I just tried with https;//de.m.wikipedia/wiki/Deutschland (also to try utf-8 issues) and I got the same problem.

I see the following in the console:

```
E/IPCThreadState( 6710): Process seems to be sending too many oneway calls.
```

This message comes from the android library, I'm not sure if and how I to get around this.

I suppose it's because of the size of the text... in the meantime we'll stick with the copy button!
