### ISSUE TITLE
MD Preview Mode

### ISSUE THREAD

**Issue by Fmstrat** [sanzoghenzo/markdownr#55]
Request for the viewport to leverage an MD viewer to display the rendered MD vs the raw text. This would make Markdownr a viable web reader with an easy save/archive option.

**Comment by sanzoghenzo** [comment]
Thanks @Fmstrat for this issue, it was easier than expected (just another dependency to add an a few lines of code)!

I've introduced it as an option, disabled by default (My use case is to just pass the markdown into a destination app, so I don't care much to see the rendered text in my app).
