### ISSUE TITLE
Error when displaying codeblock

### ISSUE THREAD

**Issue by ikaro2004** [sanzoghenzo/markdownr#67]
On some pages when converting them to markdown it only shows the first line of the codeblock.

Ej.
https://www.bitsgalore.org/2023/03/09/extracting-text-from-epub-files-in-python

**Comment by sanzoghenzo** [comment]
Hi, sorry for the radio silence!

Unfortunately, this is something beyond my control, it seems that the html2md library that I use don't work well with `<span>` tags inside `<code>` tag.

I've forwarded the issue to the library developer.

BTW, that webpage markdown source can be found [here](https://github.com/bitsgalore/bitsgalore.github.io/blob/master/_posts/2023/2023-03-09-extracting-text-from-epub-files-in-python.md) :wink:

**Comment by sanzoghenzo** [comment]
Until (and if) this is fixed upstream, I've managed to use a custom html2md rule to make it work :wink: 

In the next few days I'll try to add some other fixes/features before making a release.
