### ISSUE TITLE
Error Occurs When Sharing an Article from the Bundle App

### ISSUE THREAD

**Issue by Medullitus** [sanzoghenzo/markdownr#71]
Hello, when I try to share articles in the "Bundle" app, I encounter the error "FormatException: Illegal scheme character (at character 10)." Can you help about it? Thank you.

**Comment by sanzoghenzo** [comment]
Hi @Medullitus, 
What do you mean by "bundle app"? Is it an actual android application? I can't find it anywhere...
Does it occur for every url or for specific domains?

**Comment by Medullitus** [comment]
Bundle is a news RSS application. The Android Play Store link is below:

https://play.google.com/store/apps/details?id=com.dwarfplanet.bundle&hl=tr&gl=US

Unfortunately, the same error is occurring for every content. If you test it yourself, you can see it more clearly. Thank you very much for your response.

**Comment by sanzoghenzo** [comment]
Thank you for the clarification, I  just installed it and I can reproduce the issue.

Unfortunately, the share button doesn't send the url link of the article webpage, it just send the title as text, so it is impossible for markdownr to download the page and convert it.

You have to tap the three dots in the upper right corner, tap the copy link and then paste it in markdownr.

I can't do anything to change this behavior, reach out the bundle team and ask them to fix it.

**Comment by Medullitus** [comment]
I thank you for the quick responses and your attention as a user. I use the application for Joplin. But I'm glad to have known a dedicated developer like you. I would have loved to see you on the Joplin team. I hope you continue to design beautiful and functional applications!
