### ISSUE TITLE
"invalid argument: no host URI specified" but I did

### ISSUE THREAD

**Issue by dm7p** [sanzoghenzo/markdownr#72]
https://peterbabic.dev/blog/updating-uefi-bios-via-fwupd-on-thinkpad-t14-gen3/

trying to convert the URL above displays the toast notification quoted in the title. the URL is valid enough to load in my browser ...

**Comment by sanzoghenzo** [comment]
Hi @dm7p, I'm sorry you ran into this issue.

Does this happen when you share the url to markdownr? What if you click on the convert button?

I recall I got this error sometimes, when I enter the app via the share intent, but then the article gets converted if I manually convert it.
If you can confirm this, it seems that the conversion function gets called too early or the url is not correctly passed to it.

**Comment by dm7p** [comment]
it's okay @sanzoghenzo , thank you for writing this useful open source software :pray:

since I forgot earlier:
version 1.6.0 (F-Droid)
Android 14

generally I only use the app through the share intent. if I press "convert" manually it fails. however, if I delete the URL from the text entry field, and re-paste it, then I hit convert and it works

**Comment by sanzoghenzo** [comment]
Quick update: another user reported the same issue via email.

I can (randomly) reproduce this issue, but it is enough to edit the url in the input box by removing and re-adding a single character to make it work again.

It seems that the value in the input box is not tied correctly to the variable used to download the page.
I'll see if I can find some way to fix this.

**Comment by jeff9315** [comment]
Actually, any GitHub page is a perfect example of this happening. For example, this page shares:

`Issues · sanzoghenzo/markdownr https://github.com/sanzoghenzo/markdownr/issues`

In an ideal world, the link text would become the page name and the link url would be parsed into markdown
